kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker



# This is the config to start a k8s cluster locally using docker, kind as in the cli stands for "k8s inside docker"
#  kind create cluster --config clusters.yml --name local