apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-k8s
  template:
    metadata:
      labels:
        app: backend-k8s
    spec:
      containers:
      - name: backend-k8s
        image: harshitbreaksprod/backend-k8s:2
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: env-file
          readOnly: true
          # mountPath: "/app/" replaces everything with the volume mount
          mountPath: "/app/secret" # thats why creating a new folder so our code is preserved. need to specify in code where to pick .env from
      volumes:
      - name: env-file
        secret:
          secretName: backend-secret
---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-k8s
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007  # This port can be any valid port within the NodePort range
  type: NodePort
