apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data: # each key value pair is treated like file and its contents when volume mount is used for deployment manifest
  db_url: "cG9zdGdyZXM6Ly91c2VybmFtZTpwYXNzd29yZEBob3N0OnBvcnQvZGI=" # This is the base64 encode db connection string
  .env: "REFUQUJBU0VfVVJMPSJzb21lc2VjcmV0dGhhdG5lZWRzdG9iZWVuY29kZWR0b2Jhc2U2NCIKQ0FDSEVfU0laRT0ic29tZXNlY3JldHRoYXRuZWVkc3RvYmVlbmNvZGVkdG9iYXNlNjQiClBBWU1FTlRfR0FURVdBWV9VUkw9InNvbWVzZWNyZXR0aGF0bmVlZHN0b2JlZW5jb2RlZHRvYmFzZTY0IgpNQVhfQ0FSVF9JVEVNUz0ic29tZXNlY3JldHRoYXRuZWVkc3RvYmVlbmNvZGVkdG9iYXNlNjQiClNFU1NJT05fVElNRU9VVD0ic29tZXNlY3JldHRoYXRuZWVkc3RvYmVlbmNvZGVkdG9iYXNlNjQi" # Reading file as a secret that is encoded to base64
